# Generated by Django 6.1.1 on 2026-09-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_lifting_and_unloading_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskarea',
            name='requires_gas_monitoring',
        ),
        migrations.AddField(
            model_name='riskarea',
            name='required_gas_measurements',
            field=models.JSONField(blank=True, default=list, help_text='Chaves de permits.constants.GAS_LIMITS aplicáveis a esta área (oxygen, carbon_monoxide, hydrogen_sulfide, lower_explosive_limit). Vazio = a etapa de medição atmosférica não aparece para esta área.', verbose_name='medições de gás exigidas'),
        ),
    ]
