# Generated by Django 6.1.1 on 2026-09-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_required_gas_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='riskarea',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='riskarea',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_areas', to='core.organization'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='riskarea',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('organization', 'name')},
        ),
    ]
