# Generated by Django 6.1.1 on 2026-09-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backfill_default_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskarea',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_areas', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.organization'),
        ),
    ]
