# Generated by Django 6.1.1 on 2026-09-06 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_reference_data'),
        ('workers', '0002_seed_document_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('risk_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='core.riskarea')),
            ],
            options={
                'ordering': ['risk_area', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descrição do serviço')),
                ('intervention_type', models.CharField(blank=True, choices=[('Manutenção corretiva', 'Manutenção corretiva'), ('Manutenção preventiva', 'Manutenção preventiva'), ('Limpeza técnica', 'Limpeza técnica'), ('Inspeção', 'Inspeção'), ('Montagem / obra', 'Montagem / obra')], max_length=50, verbose_name='tipo de intervenção')),
                ('contractor_company', models.CharField(blank=True, max_length=150, verbose_name='empresa executante')),
                ('specific_location', models.CharField(blank=True, max_length=200, verbose_name='local específico')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='início previsto')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='término previsto')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_meters', models.FloatField(blank=True, null=True)),
                ('location_fixed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_approval', 'Aguardando aprovação'), ('open', 'Aberta'), ('closed', 'Encerrada'), ('incident', 'Ocorrência'), ('rejected', 'Rejeitada')], default='draft', max_length=20)),
                ('forced_ventilation_on', models.BooleanField(default=False)),
                ('forced_ventilation_started_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_permits', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_permits', to=settings.AUTH_USER_MODEL)),
                ('risk_areas', models.ManyToManyField(related_name='permits', to='core.riskarea')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='core.unit')),
            ],
            options={
                'verbose_name': 'PET',
                'verbose_name_plural': 'PETs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='permit_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='permits.workpermit')),
            ],
        ),
        migrations.CreateModel(
            name='PermitLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='permits.workpermit')),
            ],
            options={
                'verbose_name_plural': 'log entries',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('work_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='permits.workpermit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='O₂ (%)')),
                ('carbon_monoxide', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='CO (ppm)')),
                ('hydrogen_sulfide', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='H₂S (ppm)')),
                ('lower_explosive_limit', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='LEL (%)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_within_limits', models.BooleanField(default=True, editable=False)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_readings', to=settings.AUTH_USER_MODEL)),
                ('work_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_readings', to='permits.workpermit')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.worker')),
                ('work_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='permits.workpermit')),
            ],
            options={
                'unique_together': {('work_permit', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='PermitSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('technician', 'Técnico de segurança emitente'), ('executor', 'Executante responsável')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(blank=True, max_length=20)),
                ('signature_image', models.ImageField(upload_to='signatures/%Y/%m/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('integrity_hash', models.CharField(editable=False, max_length=64)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker')),
                ('work_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='permits.workpermit')),
            ],
            options={
                'unique_together': {('work_permit', 'role')},
            },
        ),
        migrations.CreateModel(
            name='PermitFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('risk_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.riskarea')),
                ('work_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='permits.workpermit')),
            ],
            options={
                'unique_together': {('work_permit', 'risk_area', 'field_key')},
            },
        ),
    ]
