# Generated by Django 6.1.1 on 2026-09-08 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_lifting_and_unloading_areas'),
        ('permits', '0002_seed_checklist_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitemtemplate',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='permitchecklistitem',
            name='checked_at',
        ),
        migrations.RemoveField(
            model_name='permitchecklistitem',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='checklistitemtemplate',
            name='regulatory_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='permitchecklistitem',
            name='answer',
            field=models.CharField(blank=True, choices=[('yes', 'Sim'), ('no', 'Não'), ('na', 'N/A')], max_length=10),
        ),
        migrations.AddField(
            model_name='permitchecklistitem',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permitchecklistitem',
            name='regulatory_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='checklistitemtemplate',
            name='risk_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='core.riskarea'),
        ),
    ]
