# Generated by Django 6.1.1 on 2026-09-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_lifting_and_unloading_areas'),
        ('permits', '0004_reseed_checklist_templates'),
        ('workers', '0003_seed_nr11_nr20_document_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryPPEItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('risk_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_ppe_items', to='core.riskarea')),
            ],
            options={
                'verbose_name': 'EPI obrigatório',
                'verbose_name_plural': 'EPIs obrigatórios',
                'ordering': ['risk_area', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PermitPPEVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ppe_verifications/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=False)),
                ('items_result', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.CharField(blank=True, max_length=500)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('work_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_verifications', to='permits.workpermit')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
