# Generated by Django 6.1.1 on 2026-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0006_seed_mandatory_ppe_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitSequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
