# Generated by Django 6.1.1 on 2026-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0008_seed_permit_sequence_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasreading',
            name='carbon_monoxide',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='CO (ppm)'),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='hydrogen_sulfide',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='H₂S (ppm)'),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='lower_explosive_limit',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='LEL (%)'),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='oxygen',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='O₂ (%)'),
        ),
    ]
