# Generated by Django 6.1.1 on 2026-09-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_alter_riskarea_slug_alter_unit_name_and_more'),
        ('permits', '0009_alter_gasreading_carbon_monoxide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitemtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='core.organization'),
        ),
        migrations.AddField(
            model_name='mandatoryppeitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_ppe_items', to='core.organization'),
        ),
        migrations.AddField(
            model_name='permitsequencecounter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='permitsequencecounter',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workpermit',
            name='permit_number',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='permitsequencecounter',
            unique_together={('organization', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='workpermit',
            unique_together={('organization', 'permit_number')},
        ),
    ]
