# Generated by Django 6.1.1 on 2026-09-07 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_reference_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('siren_silenced_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triggered_evacuations', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evacuation_events', to='core.unit')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
