# Generated by Django 6.1.1 on 2026-09-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_riskarea_organization_alter_unit_organization'),
        ('dashboard', '0004_alter_evacuationevent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationevent',
            name='source',
            field=models.CharField(choices=[('gas_alarm', 'Alarme atmosférico automático'), ('manual', 'Alarme manual')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='PhysicalAlertEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome do gateway')),
                ('webhook_url', models.URLField(verbose_name='URL do webhook')),
                ('secret_token', models.CharField(blank=True, help_text='Enviado no header X-PET-Digital-Signature (HMAC-SHA256 do corpo) para o gateway validar a origem.', max_length=64, verbose_name='token secreto')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_status', models.CharField(blank=True, max_length=10)),
                ('last_delivery_error', models.CharField(blank=True, max_length=300)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_alert_endpoints', to='core.organization')),
                ('unit', models.ForeignKey(blank=True, help_text='Vazio = recebe alarmes de todas as unidades desta empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_alert_endpoints', to='core.unit')),
            ],
            options={
                'verbose_name': 'endpoint de alerta físico',
                'verbose_name_plural': 'endpoints de alerta físico',
                'ordering': ['organization', 'name'],
            },
        ),
    ]
