# Generated by Django 6.1.1 on 2026-09-08 18:43

import core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_evacuationevent_source_physicalalertendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalalertendpoint',
            name='secret_token',
            field=core.encrypted_fields.EncryptedCharField(blank=True, help_text='Enviado no header X-PET-Digital-Signature (HMAC-SHA256 do corpo) para o gateway validar a origem.', max_length=500, verbose_name='token secreto'),
        ),
    ]
