# Generated by Django 6.1.1 on 2026-09-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_set_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
