# Generated by Django 6.1.1 on 2026-09-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_pin_hash_user_pin_set_at'),
        ('core', '0006_organization_alter_riskarea_slug_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization'),
        ),
    ]
