# Generated by Django 6.1.1 on 2026-09-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_encrypted',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
