# Generated by Django 6.1.1 on 2026-09-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_alter_riskarea_slug_alter_unit_name_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AlterField(
            model_name='periodreport',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Vazio = todas as unidades desta empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit'),
        ),
    ]
