# Generated by Django 6.1.1 on 2026-09-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_riskarea_organization_alter_unit_organization'),
        ('reports', '0003_backfill_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
    ]
