# Generated by Django 6.1.1 on 2026-09-06 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_reference_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nome completo')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='matrícula')),
                ('job_title', models.CharField(max_length=100, verbose_name='função')),
                ('company', models.CharField(max_length=150, verbose_name='empresa')),
                ('employment_type', models.CharField(choices=[('own', 'Próprio'), ('contractor', 'Terceiro')], default='own', max_length=20, verbose_name='vínculo')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='core.unit')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(verbose_name='validade')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.documenttype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workers.worker')),
            ],
            options={
                'verbose_name': 'documento do funcionário',
                'verbose_name_plural': 'documentos dos funcionários',
                'ordering': ['valid_until'],
                'unique_together': {('worker', 'document_type')},
            },
        ),
    ]
