# Generated by Django 6.1.1 on 2026-09-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_alter_riskarea_slug_alter_unit_name_and_more'),
        ('workers', '0003_seed_nr11_nr20_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='core.organization'),
        ),
        migrations.AddField(
            model_name='worker',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='registration_number',
            field=models.CharField(max_length=20, verbose_name='matrícula'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('organization', 'registration_number')},
        ),
    ]
