# Generated by Django 6.1.1 on 2026-09-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_riskarea_organization_alter_unit_organization'),
        ('workers', '0005_backfill_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='core.organization'),
        ),
    ]
